In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#from autoviz import AutoViz_Class
from ydata_profiling import ProfileReport

In [16]:
df=pd.read_csv('./heart_disease/cleaned_data.csv')
df.head(10)

'''
Dataset columns:

    age: The person’s age in years
    sex: The person’s sex (1 = male, 0 = female)
    cp: chest pain type
    — Value 0: asymptomatic
    — Value 1: atypical angina
    — Value 2: non-anginal pain
    — Value 3: typical angina
    trestbps: The person’s resting blood pressure (mm Hg on admission to the hospital)
    chol: The person’s cholesterol measurement in mg/dl
    fbs: The person’s fasting blood sugar (> 120 mg/dl, 1 = true; 0 = false)
    restecg: resting electrocardiographic results
    — Value 0: showing probable or definite left ventricular hypertrophy by Estes’ criteria
    — Value 1: normal
    — Value 2: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
    thalach: The person’s maximum heart rate achieved
    exang: Exercise induced angina (1 = yes; 0 = no)
    oldpeak: ST depression induced by exercise relative to rest (‘ST’ relates to positions on the ECG plot. See more here)
    slope: the slope of the peak exercise ST segment — 0: downsloping; 1: flat; 2: upsloping
    0: downsloping; 1: flat; 2: upsloping
    ca: The number of major vessels (0–3)
    thal: A blood disorder called thalassemia Value 0: NULL (dropped from the dataset previously
    Value 1: fixed defect (no blood flow in some part of the heart)
    Value 2: normal blood flow
    Value 3: reversible defect (a blood flow is observed but it is not normal)
    target: Heart disease (1 = no, 0= yes)

'''

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
5,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
6,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3
7,57.0,0.0,4.0,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0
8,63.0,1.0,4.0,130.0,254.0,0.0,2.0,147.0,0.0,1.4,2.0,1.0,7.0,2
9,53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1

In [8]:
plt.figure(figsize=(16, 6))
heatmap = sns.heatmap(df.corr(), vmin=-1, vmax=1, annot=True, cmap='BrBG')
heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':18}, pad=12);# save heatmap as .png file
# dpi - sets the resolution of the saved image in dots/inches
# bbox_inches - when set to 'tight' - does not allow the labels to be croppedplt.savefig('heatmap.png', dpi=300, bbox_inches='tight')

In [14]:

profile = ProfileReport(df, title="Pandas Profiling Report")
profile.to_file("report.html")

Summarize dataset: 100%|██████████| 48/48 [00:17<00:00,  2.70it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:10<00:00, 10.31s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 15.87it/s]